import { StudentScholarshipRow } from './types';

export const INITIAL_SCHOLARSHIP_DATA: StudentScholarshipRow[] = [
  {
    id: 'student-1',
    region: 'PB + J&K',
    center: 'Anantnag Vidyapeeth',
    building: 'Anantnag Vidyapeeth',
    studentName: 'Midhat Altaf',
    regNo: '23156886',
    batchName: '90-UF101ES',
    class: '10th',
    scholarship: 'Flat 15k',
    mentor: 'Umar Sir',
    mentorMailid: 'umar.lone@pw.live',
    pwid: 'Pw30917',
    whatsappIntimation: false,
    ptmStatus: '',
    parentRemarks: '',
    paymentDate: '',
    discontinueReason: '',
    retentionProbability: '',
    proposedScholarship: '',
    extraScholarshipDemand: false,
    extraScholarshipStatus: '',
    finalRetentionStatus: '',
    finalScholarship: '',
    counselorName: '',
    counselorPwid: '',
    newRegno: ''
  },
  {
    id: 'student-2',
    region: 'PB + J&K',
    center: 'Anantnag Vidyapeeth',
    building: 'Anantnag Vidyapeeth',
    studentName: 'Aarfa Tabasum',
    regNo: '23180367',
    batchName: '90-UF101ES',
    class: '10th',
    scholarship: 'Flat 15k',
    mentor: 'Umar Sir',
    mentorMailid: 'umar.lone@pw.live',
    pwid: 'Pw30917',
    whatsappIntimation: false,
    ptmStatus: '',
    parentRemarks: '',
    paymentDate: '',
    discontinueReason: '',
    retentionProbability: '',
    proposedScholarship: '',
    extraScholarshipDemand: true,
    extraScholarshipStatus: 'Pending',
    finalRetentionStatus: '',
    finalScholarship: '',
    counselorName: '',
    counselorPwid: '',
    newRegno: ''
  },
  {
    id: 'student-3',
    region: 'PB + J&K',
    center: 'Anantnag Vidyapeeth',
    building: 'Anantnag Vidyapeeth',
    studentName: 'Munisa Rasool',
    regNo: '23162970',
    batchName: '90-UF101ES',
    class: '10th',
    scholarship: '100% on Tuition Fees',
    mentor: 'Umar Sir',
    mentorMailid: 'umar.lone@pw.live',
    pwid: 'Pw30917',
    whatsappIntimation: false,
    ptmStatus: '',
    parentRemarks: '',
    paymentDate: '',
    discontinueReason: '',
    retentionProbability: '',
    proposedScholarship: '',
    extraScholarshipDemand: false,
    extraScholarshipStatus: '',
    finalRetentionStatus: '',
    finalScholarship: '',
    counselorName: '',
    counselorPwid: '',
    newRegno: ''
  },
  {
    id: 'student-4',
    region: 'PB + J&K',
    center: 'Anantnag Vidyapeeth',
    building: 'Anantnag Vidyapeeth',
    studentName: 'Syed Shehoona shaan',
    regNo: '23158675',
    batchName: '90-UF101ES',
    class: '10th',
    scholarship: 'Flat 15k',
    mentor: 'Umar Sir',
    mentorMailid: 'umar.lone@pw.live',
    pwid: 'Pw30917',
    whatsappIntimation: false,
    ptmStatus: '',
    parentRemarks: '',
    paymentDate: '',
    discontinueReason: '',
    retentionProbability: '',
    proposedScholarship: '',
    extraScholarshipDemand: true,
    extraScholarshipStatus: 'Approved',
    finalRetentionStatus: '',
    finalScholarship: 'Flat 15k',
    counselorName: '',
    counselorPwid: '',
    newRegno: ''
  },
  {
    id: 'student-5',
    region: 'PB + J&K',
    center: 'Pulwama Tuition Center',
    building: 'Pulwama Tuition Center',
    studentName: 'Zikrat Un Nisa',
    regNo: '23180670',
    batchName: 'T44-UF21ES',
    class: '10th',
    scholarship: '100% on Tuition Fees',
    mentor: 'Umar Sir',
    mentorMailid: '',
    pwid: '',
    whatsappIntimation: false,
    ptmStatus: '',
    parentRemarks: '',
    paymentDate: '',
    discontinueReason: '',
    retentionProbability: '',
    proposedScholarship: '',
    extraScholarshipDemand: false,
    extraScholarshipStatus: '',
    finalRetentionStatus: '',
    finalScholarship: '',
    counselorName: '',
    counselorPwid: '',
    newRegno: ''
  },
  {
    id: 'student-6',
    region: 'PB + J&K',
    center: 'Anantnag Vidyapeeth',
    building: 'Anantnag Vidyapeeth',
    studentName: 'Sadia Manzoor',
    regNo: '23157570',
    batchName: '90-UF101ES',
    class: '10th',
    scholarship: '100% on Tuition Fees',
    mentor: 'Umar Sir',
    mentorMailid: 'umar.lone@pw.live',
    pwid: 'Pw30917',
    whatsappIntimation: false,
    ptmStatus: '',
    parentRemarks: '',
    paymentDate: '',
    discontinueReason: '',
    retentionProbability: '',
    proposedScholarship: '',
    extraScholarshipDemand: false,
    extraScholarshipStatus: '',
    finalRetentionStatus: '',
    finalScholarship: '',
    counselorName: '',
    counselorPwid: '',
    newRegno: ''
  }
];
